version: 2.1
jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - run:
          name: Create Postman Collection Report
          command: |
            npm install -g newman newman-reporter-htmlextra
            newman run https://www.getpostman.com/collections/eb329dc9b72aa84c6fca -r cli,htmlextra --reporter-htmlextra-export collection-health-report.html
          when: always
workflows:
  build_test:
    jobs:
      - build