version: 2.1
jobs:
  Postman_Collection:
    docker:
      - image: node:latest
    resource_class: small
    steps:
      - run:
          name: Create Postman Collection Report
          command: |
            npm install -g newman newman-reporter-htmlextra
            newman run https://www.getpostman.com/collections/eb329dc9b72aa84c6fca -r cli,htmlextra --reporter-htmlextra-export collection-report.html
          when: always
      - store_artifacts:
          path: collection-report.html
      - store_test_results:
          path: collection-report.html
workflows:
  Postman_Collection_Test:
    triggers:
      - schedule:
          branches:
            only:
              - master
    jobs:
      - Postman_Collection